sudo: required

services:
  - docker

language: python

install:
  - pip install codacy-coverage
  - chmod +x ./tools/run/build.sh
  - chmod +x ./tools/run/test.sh
  - chmod +x ./backend/test.sh

script:
  - ./tools/run/test.sh

after_success:
  - python-codacy-coverage -r backend/coverage.xml
