sudo: required

services:
  - docker

language: python

install:
{% if cookiecutter.use_codacy == 'y' %}
  - pip install codacy-coverage
  - npm install -g codacy-coverage
{% endif %}
  - chmod +x ./tools/*/*.sh
  - chmod +x ./backend/test.sh

script:
  - ./tools/run/test.sh
{% if cookiecutter.use_codacy == 'y' %}
after_success:
  - python-codacy-coverage -r backend/coverage.xml
  - cat frontend/coverage/lcov.info | codacy-coverage
{% endif %}