sudo: required

services:
  - docker

language: python

install:
  - pip install backports.functools_lru_cache
  - pip install cookiecutter
  - pip install codacy-coverage
  - chmod +x ./test.sh

script:
  - ./test.sh
  - python-codacy-coverage -r target/project_name/backend/coverage.xml
